routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'welcome');

Route::resource('/users', 'UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
  use Notifiable;

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = ['name', 'email', 'birthday', 'cpf', 'is_active', 'password'];

  /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
  protected $hidden = [
    'password', 'remember_token'
  ];

  public function setPasswordAttribute($password)
  {
    if (!empty($password))
    {
      $this->attributes['password'] = bcrypt($password);
    }
  }

  /**
   * Search on fields: name, email, cpf
   * @param $search
   * @return user object with query params
   **/

  public function search($search) {
    return User::where('name','like', '%'.$search.'%')
      ->orWhere('email', 'like', '%'.$search.'%')
      ->orWhere('cpf', 'like', '%'.$search.'%')
      ->paginate(5)
      ->appends('search', $search);
  }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Foundation\Auth\RegistersUsers;
use App\User;
use App\Http\Requests\UserValidation;
use GuzzleHttp\Client;

class UserController extends Controller
{

  public function __construct() {
    $this->user = new User();
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
    if($request->has('search') ) {
      $users = $this->user->search($request->search);
    }else{
      $users = $this->user->paginate(5);
    }
    return view('user.index', ['users' => $users]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('user.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(UserValidation $request)
  {
    $request->offsetSet('is_active', 1);

    $user = $this->user->create($request->all());

    return redirect('users');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    header("Content-Type: image/png");
    $getImage = $this->getImageFromAPI($id);
    $type = pathinfo($getImage->data->image_path, PATHINFO_EXTENSION);
    $data = file_get_contents($getImage->data->image_path);
    echo $data;
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $getImage = $this->getImageFromAPI($id);

    if(isset($getImage->errors)) {
      $image = '';
    }else {
      $image = $getImage->data->image_path;
    }

    return view('user.edit', ['user' => $this->user->findOrFail($id)], ['image_path' => $image]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(UserValidation $request, $id)
  {
    $this->user->fill($request->all());
    $this->user->find($id)->update($request->all());

    return redirect()->route('users.index');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $this->user->find($id)->delete();

    return redirect()->route('users.index');
  }

  public function getImageFromAPI($id) {
    $client = new Client();
    $res = $client->request('GET', env('SOUK_API').'images/'.$id, ["http_errors" => false]);

    $res = json_decode($res->getBody()->getContents());

    return $res;
  }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>SOUK</title>

  <!-- Styles -->
  <link href="{{ mix('css/app.css') }}" rel="stylesheet">

</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header"> <button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>      <a href="#" class="navbar-brand">Brand</a> </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
        <ul class="nav navbar-nav">
          <li class="active"><a href="<?php echo url('/'); ?>">Home</a></li>
          <li><a href="<?php echo url('users/'); ?>">Usuários</a></li>
        </ul>
      </div>
    </div>
  </nav>
  {{-- @include('shared.menu') --}}
  <div id="app">
    @yield('content')
  </div>

  <script type="text/javascript" src="{{ mix('js/app.js') }}"></script>
  <script type="text/javascript">
    jQuery(document).ready(function ($){
      $("#imageForm").submit(function(e){
        e.preventDefault();
        var formData = new FormData(this);

        var url = $(this).attr('action');

        $.ajax({
            url: url,
            type: 'POST',
            data:new FormData($("#imageForm")[0]),
            success: function (data) {
              console.log();
              console.log($('#photo'));
              $('#photo').attr('src', data.data['image_path']);
            },
            cache: false,
            contentType: false,
            processData: false,
        });
      });
    });
  </script>
</body>
</html>

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <h1>Adicionar usuário</h1>

    <form class="" method="POST" action="{{ route('users.store') }}">
      {{ csrf_field() }}

      @include('layouts.errors.error')

      <div class="col-sm-6">
        <div class="form-group">
          <label for="name" class="control-label">Nome</label>
          <input id="name" type="text" class="form-control" name="name" value="{{old('name')}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="email" class="control-label">E-mail</label>
          <input id="email" type="text" class="form-control" name="email" value="{{old('email')}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="birthday" class="control-label">Aniversário</label>
          <input id="birthday" type="text" class="form-control" name="birthday" value="{{old('birthday')}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="cpf" class="control-label">CPF</label>
          <input id="cpf" type="text" class="form-control" name="cpf" value="{{old('cpf')}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
          <label for="password" class="control-label">Senha*</label>
          <input id="password" type="password" class="form-control" name="password" required>

          @if ($errors->has('password'))
            <span class="help-block">
              <strong>{{ $errors->first('password') }}</strong>
            </span>
          @endif
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="password-confirm" class="control-label">Confirmar Senha</label>
          <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
        </div>
      </div>

      <div class="col-sm-4 pull-right text-right" style="margin-top: 40px;">
        <button type="submit" class="col-xs-12 btn btn-md btn-primary">Enviar</button>
      </div>
    </form>

  </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <h1>Editar usuário</h1>

    <form id="imageForm" class="" method="POST" action="{{env('SOUK_API')}}images/{{$user->id}}">
      {{ csrf_field() }}
      {{ method_field('PUT')}}
      <div class="col-sm-6">
        <img id="photo" src="{{$image_path}}" width="80" />
        <div class="form-group">
          <label for="file" class="control-label">Image</label>
          <input id="file" type="file" class="form-control" name="file" autofocus />
          <input type="submit" value="Enviar" class="btn btn-md btn-primary send" />
        </div>
      </div>
    </form>

    <form class="" method="POST" action="{{ route('users.update', $user->id) }}">
      {{ csrf_field() }}

      {{ method_field('PUT')}}

      @include('layouts.errors.error')

      <div class="col-sm-12">
        <div class="form-group">
          <div class="checkbox">
            <label>
              <input name="is_active" type="checkbox" {{ ($user->is_active == true) ? 'checked' : '' }} value="{{$user->is_active}}"> Ativo
            </label>
          </div>
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="name" class="control-label">Nome</label>
          <input id="name" type="text" class="form-control" name="name" value="{{$user->name}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="email" class="control-label">E-mail</label>
          <input id="email" type="text" class="form-control" name="email" value="{{$user->email}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="birthday" class="control-label">Aniversário</label>
          <input id="birthday" type="text" class="form-control" name="birthday" value="{{$user->birthday}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="cpf" class="control-label">CPF</label>
          <input id="cpf" type="text" class="form-control" name="cpf" value="{{$user->cpf}}" autofocus />
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
          <label for="password" class="control-label">Senha*</label>
          <input id="password" type="password" class="form-control" name="password">

          @if ($errors->has('password'))
            <span class="help-block">
              <strong>{{ $errors->first('password') }}</strong>
            </span>
          @endif
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="password-confirm" class="control-label">Confirmar Senha</label>
          <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
        </div>
      </div>

      <div class="col-sm-4 pull-right text-right" style="margin-top: 40px;">
        <button type="submit" class="col-xs-12 btn btn-md btn-primary">Enviar</button>
      </div>
    </form>

  </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <h1>Usuários</h1>
      <div class="row" style="margin-bottom: 15px;">
        <div class="col-lg-6">

          <form class="form" method="get" action="{{route('users.index')}}">
            <div class="input-group">
              <input name="search" type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Buscar</button>
              </span>
            </div>
          </form>

        </div>
      </div>

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <td>&nbsp;</td>
            <td>Name</td>
            <td>Email</td>
            <td>Data de Nascimento</td>
            <td>CPF</td>
            <td>Ações</td>
          </tr>
        </thead>
        <tbody>
          @foreach($users as $key => $value)
          <tr>
            <td><img src="{{route('users.show', $value->id)}}" width="50" /></td>
            <td>{{ $value->name }}</td>
            <td>{{ $value->email }}</td>
            <td>{{ $value->birthday }}</td>
            <td>{{ $value->cpf }}</td>
            <td>
              <form action="{{ route('users.destroy', $value->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE')}}
                <a href="{{route('users.edit', $value->id)}}" class="btn btn-warning">Editar</a>
                <button class="btn btn-danger" type="submit">Delete</button>
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
        <tfoot>
          <td colspan="6">
            <a href="{{route('users.create')}}" class="btn btn-sm btn-success col-xs-12">
              <i class="glyphicon glyphicon-plus"></i>
            </a>
          </td>
        </tfoot>
      </table>

      {{ $users->links() }}

    </div>
  </div>
</div>
@endsection